[package]
name = "flappy-bird-rust"
version = "0.1.0"
authors = ["szybalint"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_engine = "1.5.1"